@startuml 
skinparam groupInheritance 2



abstract API{}
abstract Resource{}




class Sensors <<API>>{
    Sensor sensor
}
class Sensor <<Resource>>{
    GET()
    POST()
    PUT()
    DELETE()
}

class Logger{
    InternalDBConnection InternalDBConnection
}

class DataHandler{
    --private attributes--
    InternalDBConnection InternalDBConnection
    ExternalDBConnection[] ExternalDBConnections

}

API <|-- Sensors
Sensors <|-- Sensor

class InternalDBConnection{}
class ExternalDBConnection {}
class ExternalDB_MSSQL{}
class ExternalDB_MySQL{}

class ExternalDB_MSSQL extends ExternalDBConnection
class ExternalDB_MySQL extends ExternalDBConnection

@enduml