@startuml 


abstract API{}
abstract Resource{}

class Logger{

}

class DataHandler{
    
InternalDataBaseConnection InternalDBConnection
ExternalDatabaseConnection[] ExternalDBConnections

}

class Sensors <<API>>{
    Sensor sensor
}
class Sensor <<Resource>>{
    GET()
    POST()
    PUT()
    DELETE()
}

Interface InternalDataBaseConnection
Interface ExternalDatabaseConnection

@enduml