@startuml 


API <|-- Sensors
Sensors <|-- Sensor

abstract API{}
abstract Resource{}


class Logger{

}

class DataHandler{
    --private attributes--
    InternalDataBaseConnection InternalDBConnection
    ExternalDatabaseConnection[] ExternalDBConnections

}

class Sensors <<API>>{
    Sensor sensor
}
class Sensor <<Resource>>{
    GET()
    POST()
    PUT()
    DELETE()
}

Interface InternalDataBaseConnection
Interface ExternalDatabaseConnection

@enduml